language: node_js

node_js:
    - stable

cache:
  directories:
  - node_modules

before_script:
    - "npm install --prod"

script:
    - "npm run prod"

deploy:
    - provider: s3
      access_key_id: $S3_ID
      secret_access_key: $S3_SECRET
      bucket: dev.thinkingcapp.com
      endpoint: http://dev.thinkingcapp.com.s3-website-us-east-1.amazonaws.com
      skip_cleanup: true
      cache_control: max-age=360
      detect_encoding: true
      acl: public_read
      on:
          branch: dev
    - provider: s3
      access_key_id: $S3_ID
      secret_access_key: $S3_SECRET
      bucket: thinkingcapp.com
      endpoint: http://thinkingcapp.com.s3-website-us-east-1.amazonaws.com
      skip_cleanup: true
      detect_encoding: true
      acl: public_read
      on:
          branch: master

notifications:
  email:
    recipients:
      - kyle@dataskeptic.com
    on_success: always
    on_failure: always
